### ISSUE TITLE
[bug] openwisp-websocket image not working with django 4.0+

### ISSUE THREAD

**Issue by AdUser** [openwisp/docker-openwisp#462]
**Describe the bug**

Django configuration used by image openwisp-websocket uses obsolete "url" helper: https://github.com/openwisp/docker-openwisp/blob/4092f9b5ff88356871f9c7624307f7b831464251/images/openwisp_websocket/urls.py#L1

Recent versions [suggests](https://docs.djangoproject.com/en/5.2/ref/urls/#module-django.conf.urls) use either `path` or `re_path`

**Steps To Reproduce**

Logs of image "openwisp/openwisp-nginx":

```
[04c442120dbd] - - [22/May/2025:16:03:27 +1000] "GET /ws/controller/device/d1960279-ea9c-44ed-9245-f746eec117d5/command HTTP/1.0" status: 500 453 "-" "Mozilla/5.0 (X11; Linux x86_64; rv:128.0) Gecko/20100101 Firefox/128.0" http_x_forwarded_for: 192.168.1.7 - remote_addr: 172.18.0.1 - realip_remote_addr: 172.18.0.1 - real_ip: 192.168.1.7
```

Logs of image openwisp-websocket:

```
Exception inside application: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.12/site-packages/django/conf/urls/__init__.py)
Traceback (most recent call last):
  File "/usr/local/lib/python3.12/site-packages/asgiref/sync.py", line 518, in thread_handler
    raise exc_info[1]
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = await get_response(request)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 235, in _get_response_async
    callback, callback_args, callback_kwargs = self.resolve_request(request)
                                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/core/handlers/base.py", line 313, in resolve_request
    resolver_match = resolver.resolve(request.path_info)
                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 663, in resolve
    for pattern in self.url_patterns:
                   ^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 715, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
                       ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/utils/functional.py", line 57, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
                                         ^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/django/urls/resolvers.py", line 708, in urlconf_module
    return import_module(self.urlconf_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/opt/openwisp/openwisp/urls.py", line 1, in <module>
    from django.conf.urls import url
ImportError: cannot import name 'url' from 'django.conf.urls' (/usr/local/lib/python3.12/site-packages/django/conf/urls/__init__.py). Did you mean: 'urls'?
```

**Expected behavior**
No exception generated.

**System Informatioon:**
 - OS: Debian 12.10
 - Docker version: 20.10.24+dfsg1-1+deb12u1

**Comment by AdUser** [comment]
Possible fix is this small patch:

```
--- opt/openwisp/openwisp/urls.py.bak   2025-05-22 15:46:31.987580849 +1000
+++ opt/openwisp/openwisp/urls.py       2025-05-22 16:16:18.210825023 +1000
@@ -1,6 +1,6 @@
-from django.conf.urls import url
+from django.urls import re_path
 from django.contrib import admin
 
 urlpatterns = [
-    url(r'^admin/', admin.site.urls),
+    re_path(r'^admin/', admin.site.urls),
 ]
```

...but i'm not sure it works as intended. Exception not raised anymore, but now `/ws/notification/` endpoint returns 404

```
[564c8fcc1097] - WARNING, time: [2025-05-22 16:33:20,603],process: 7, thread: 139685816059648
Not Found: /ws/notification/
192.168.1.7:0 - - [22/May/2025:16:33:20] "GET /ws/notification/" 404 179
```
